name: .NET

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    env:
      ProjectName: Kasa

    runs-on: windows-latest

    steps:
    - name: Clone
      uses: actions/checkout@v4
        
    - name: Initialize test reporting
      uses: testspace-com/setup-testspace@v1
      with:
        domain: ${{github.repository_owner}}

    - name: Restore
      run: dotnet restore --verbosity normal

    - name: Build
      run: dotnet build --no-restore --configuration Release --verbosity normal

    - name: Pack
      run: dotnet pack ${{ env.ProjectName }} --no-build --configuration Release --verbosity normal

    - name: Test
      run: |
        dotnet test --no-build --verbosity normal --configuration Release --collect:"XPlat Code Coverage" --settings Test/coverlet.runsettings --logger "trx;LogFileName=TestResults.xml"
        Out-File -InputObject "TEST_EXIT_CODE=$LASTEXITCODE" -FilePath $env:GITHUB_ENV -Append -Encoding UTF8 
        Copy-Item Test/TestResults/*/coverage.info Test/TestResults -ErrorAction Continue
        exit 0

    - name: Upload test report
      run: testspace Test/TestResults/TestResults.xml

    - name: Upload coverage
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        files: Test/TestResults/coverage.info
        format: lcov

    - name: Stop if tests failed
      run: exit $env:TEST_EXIT_CODE

    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ProjectName }}.nupkg
        path: ${{ env.ProjectName }}/bin/Release/*.*nupkg
        if-no-files-found: error